name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd
            whoami
            ls
          host: ${{ secrets.DO_HOST }}
          pass: ${{ secrets.DO_PASSWORD }}

